version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - .:/var/www/html/wp-content/plugins/tc-shv-resultate

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
