version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./testing:/var/www/html/wp-content/
      - .:/var/www/html/wp-content/plugins/tc-shv-resultate

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment: 
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: wordpress
      