name: Build release zip

on:
  push:
    branches:
    # - trunk
    - main

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build plugin # Remove or modify this step as needed
      # composer install --no-dev
      run: |
        npm install
        npm run build
        
    - name: Download WP CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        php wp-cli.phar --info
        php wp-cli.phar plugin install dist-archive
        
    - name: Create ZIP
      run: |
        php wp-cli.phar dist-archive .
