name: Build release zip

on:
  push:
    branches:
    # - trunk
    - main

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build plugin # Remove or modify this step as needed
      # composer install --no-dev
      run: |
        npm install
        npm run build
        
    - name: Create ZIP
      run: |
        echo "➤ Generating zip file..."
        zip -r rmse-vat-results.zip . -x "node_modules/**" -x ".git/**" -x ".github/**"

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: rmse-vat-results.zip
        path: |
          .
          !node_modules/**
          !.git/**
          !.github/**
        retention-days: 5
